GET http://localhost:8080/feed-list?urls=https://www.diepresse.com/rss/Innenpolitik,https://www.derstandard.at/rss/live,https://www.derstandard.at/rss/recht

###

GET http://localhost:8080/item-list?urls=https://www.diepresse.com/rss/Politik

###

GET http://localhost:8080/item-list/10


###

GET http://localhost:8080/comments/2022-01-01

###

POST http://localhost:8080/comments
Content-Type: application/json

{
  "comment": {
    "item_id": 1,
    "description": "BAD BAD BAD",
    "title": "Comment title"
  }
}

###

GET http://localhost:8080/item-list/pages?pageSize=10&pageNo=0&urls=https://www.diepresse.com/rss/Politik&asc=false


###

GET http://localhost:8080/feed-list?urls=https%3A%2F%2Fwww.gruene-bundestag.de%2Fthemen%2Fnews%2F5885.xml%2Chttps%3A%2F%2Fwww.dfb.de%2Fnews%2Frss%2Ffeed%2F%3Ftx_news_pi1%5BoverwriteDemand%5D%5Bcategories%5D%3D10087
